import storybook from 'eslint-plugin-storybook';

import {
  architectureImportBoundary,
  nextSupabaseQualityProfile,
} from './.ai-dev-foundation/quality/eslint.config.mjs';

export default [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      '.foundation-checkout/**',
      // Runtime output written by `supabase start`/`supabase db reset`
      // (gitignored via supabase/.gitignore); not part of the project's
      // TS program.
      'supabase/.temp/**',
      // Mechanically generated by `npm run supabase:types`; its exact
      // drift check (scripts/check-supabase-types-drift.mjs) is the
      // integrity gate, not hand-authored style.
      'src/infrastructure/supabase/database.types.ts',
    ],
  },
  ...nextSupabaseQualityProfile(),
  architectureImportBoundary({
    files: ['src/domain/**/*.{ts,tsx}'],
    // Depth-independent, anchored patterns: "../**/ui" (and "/**") matches
    // "../ui", "../../ui", "../ui/x", "../../ui/x", ... regardless of how
    // deep the importing domain file is nested, without also matching an
    // unrelated external package such as "@vendor/ui/button" the way a bare
    // "**/ui/**" pattern would.
    restrictedPatterns: [
      '../**/ui',
      '../**/ui/**',
      '../**/app',
      '../**/app/**',
      '../**/infrastructure',
      '../**/infrastructure/**',
      '@/ui',
      '@/ui/**',
      '@/app',
      '@/app/**',
      '@/infrastructure',
      '@/infrastructure/**',
    ],
    message: 'Domain code must not import UI, app entrypoints, or infrastructure.',
  }),
  // No ad-hoc Supabase access from app code (Issue #33): src/app must go
  // through a typed feature-level module in src/infrastructure/supabase/,
  // never the generated row/RPC shape or the Supabase SDK directly. This is
  // the other half of the architecture boundary above - that one keeps
  // domain code out of infrastructure/UI/app, this one keeps app code from
  // reaching around the typed infrastructure layer back down to raw
  // Supabase. Both are deterministic, minimal guardrails, not a general
  // static-analysis framework.
  architectureImportBoundary({
    files: ['src/app/**/*.{ts,tsx}'],
    restrictedPatterns: [
      '@supabase/supabase-js',
      '@supabase/ssr',
      '../**/database.types',
      '../**/database.types.ts',
      '@/infrastructure/supabase/database.types',
      '@/infrastructure/supabase/database.types.ts',
    ],
    message:
      'App code must not import the Supabase SDK or generated Database types directly; call a typed feature-level module in src/infrastructure/supabase/ instead.',
  }),
  {
    files: ['src/app/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          // A static `import(...)`/`require(...)` of the SDK or generated
          // types would bypass the import-boundary rule above, since that
          // rule (no-restricted-imports) only inspects declaration-form
          // imports, not dynamic import expressions.
          selector: 'ImportExpression[source.value=/^(@supabase\\/supabase-js|@supabase\\/ssr)$/]',
          message:
            'App code must not dynamically import the Supabase SDK directly; call a typed feature-level module in src/infrastructure/supabase/ instead.',
        },
        {
          selector: 'ImportExpression[source.value=/database\\.types(\\.ts)?$/]',
          message:
            'App code must not dynamically import the generated Database types directly; call a typed feature-level module in src/infrastructure/supabase/ instead.',
        },
        {
          // Targets the `<client>.from(...).select/insert/update/delete/
          // upsert(...)` chain shape specifically - the Supabase query
          // builder's own method sequence - rather than any `.from(...)`
          // call, which would also flag unrelated, legitimate calls such as
          // Array.from(...) or Buffer.from(...) with no connection to
          // Supabase. Still catches a raw call reached through a client
          // instance app code only received as an opaque parameter/return
          // value from a typed infrastructure function, which the
          // import-based restriction above cannot see.
          selector:
            "MemberExpression[object.type='CallExpression'][object.callee.type='MemberExpression'][object.callee.property.name='from'][property.name=/^(select|insert|update|delete|upsert)$/]",
          message:
            'App code must not call .from(...).select/insert/update/delete/upsert(...) directly; add or use a typed feature-level function in src/infrastructure/supabase/ instead.',
        },
        {
          selector: "CallExpression[callee.type='MemberExpression'][callee.property.name='rpc']",
          message:
            'App code must not call .rpc(...) directly; add or use a typed feature-level function in src/infrastructure/supabase/ instead.',
        },
      ],
    },
  },
  ...storybook.configs['flat/recommended'],
];
