import storybook from 'eslint-plugin-storybook';

import {
  architectureImportBoundary,
  nextSupabaseQualityProfile,
} from './.ai-dev-foundation/quality/eslint.config.mjs';

/**
 * Deliberately a dedicated rule (its own plugin/rule name), not another
 * `no-restricted-syntax` entry for src/app: ESLint flat config replaces a
 * rule's option array wholesale when a later config for the same files sets
 * the same rule key, rather than merging it. An earlier revision put these
 * checks in `no-restricted-syntax` for `files: ['src/app/**']`, which
 * silently discarded nextSupabaseQualityProfile()'s own `no-restricted-
 * syntax` entries (the TSAsExpression/TSTypeAssertion type-assertion ban)
 * for every file under src/app - weakening the blocking quality profile
 * exactly where the ban still needs to apply. A distinct rule name cannot
 * collide with (or silently replace) the profile's, however it changes.
 *
 * Checks (Issue #33 - src/app must go through a typed feature-level module
 * in src/infrastructure/supabase/, never the generated row/RPC shape or the
 * Supabase SDK directly):
 *   - dynamic `import(...)` of the Supabase SDK or generated Database types
 *     (a static import is already caught by the no-restricted-imports
 *     architectureImportBoundary below; that rule does not inspect dynamic
 *     import expressions at all)
 *   - any `<receiver>.from(...)` call - the entry point into the Supabase
 *     query builder chain, not just a direct `.from(...).select(...)`
 *     chain, which a caller could dodge by storing the builder in a
 *     variable first (`const q = client.from('tickets'); await
 *     q.select()`). `Array`/`Buffer` are exempted so their own unrelated
 *     `.from(...)` static methods keep working; src/app has no other
 *     legitimate use of `.from(...)` today. Still catches a raw call
 *     reached through a client instance app code only received as an
 *     opaque parameter/return value from a typed infrastructure function,
 *     which the import-based restriction cannot see.
 *   - any `.rpc(...)` call
 */
const noAppSupabaseAccess = {
  meta: {
    type: 'problem',
    docs: { description: 'Disallow ad-hoc Supabase access from app code (Issue #33).' },
    schema: [],
    messages: {
      dynamicImportSdk:
        'App code must not dynamically import the Supabase SDK directly; call a typed feature-level module in src/infrastructure/supabase/ instead.',
      dynamicImportTypes:
        'App code must not dynamically import the generated Database types directly; call a typed feature-level module in src/infrastructure/supabase/ instead.',
      rawFrom:
        'App code must not call .from(...) directly (the entry point into the Supabase query builder); add or use a typed feature-level function in src/infrastructure/supabase/ instead.',
      rawRpc:
        'App code must not call .rpc(...) directly; add or use a typed feature-level function in src/infrastructure/supabase/ instead.',
    },
  },
  create(context) {
    return {
      ImportExpression(node) {
        if (node.source.type !== 'Literal' || typeof node.source.value !== 'string') {
          return;
        }
        const value = node.source.value;
        if (value === '@supabase/supabase-js' || value === '@supabase/ssr') {
          context.report({ node, messageId: 'dynamicImportSdk' });
        } else if (/database\.types(\.ts)?$/.test(value)) {
          context.report({ node, messageId: 'dynamicImportTypes' });
        }
      },
      CallExpression(node) {
        if (node.callee.type !== 'MemberExpression' || node.callee.property.type !== 'Identifier') {
          return;
        }
        const name = node.callee.property.name;
        if (name === 'rpc') {
          context.report({ node, messageId: 'rawRpc' });
          return;
        }
        if (name === 'from') {
          const receiver = node.callee.object;
          const isExemptStatic =
            receiver.type === 'Identifier' &&
            (receiver.name === 'Array' || receiver.name === 'Buffer');
          if (!isExemptStatic) {
            context.report({ node, messageId: 'rawFrom' });
          }
        }
      },
    };
  },
};

export default [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      '.foundation-checkout/**',
      // Runtime output written by `supabase start`/`supabase db reset`
      // (gitignored via supabase/.gitignore); not part of the project's
      // TS program.
      'supabase/.temp/**',
      // Mechanically generated by `npm run supabase:types`; its exact
      // drift check (scripts/check-supabase-types-drift.mjs) is the
      // integrity gate, not hand-authored style.
      'src/infrastructure/supabase/database.types.ts',
    ],
  },
  ...nextSupabaseQualityProfile(),
  architectureImportBoundary({
    files: ['src/domain/**/*.{ts,tsx}'],
    // Depth-independent, anchored patterns: "../**/ui" (and "/**") matches
    // "../ui", "../../ui", "../ui/x", "../../ui/x", ... regardless of how
    // deep the importing domain file is nested, without also matching an
    // unrelated external package such as "@vendor/ui/button" the way a bare
    // "**/ui/**" pattern would.
    restrictedPatterns: [
      '../**/ui',
      '../**/ui/**',
      '../**/app',
      '../**/app/**',
      '../**/infrastructure',
      '../**/infrastructure/**',
      '@/ui',
      '@/ui/**',
      '@/app',
      '@/app/**',
      '@/infrastructure',
      '@/infrastructure/**',
    ],
    message: 'Domain code must not import UI, app entrypoints, or infrastructure.',
  }),
  // No ad-hoc Supabase access from app code (Issue #33): src/app must go
  // through a typed feature-level module in src/infrastructure/supabase/,
  // never the generated row/RPC shape or the Supabase SDK directly. This is
  // the other half of the architecture boundary above - that one keeps
  // domain code out of infrastructure/UI/app, this one keeps app code from
  // reaching around the typed infrastructure layer back down to raw
  // Supabase. Both are deterministic, minimal guardrails, not a general
  // static-analysis framework.
  architectureImportBoundary({
    files: ['src/app/**/*.{ts,tsx}'],
    restrictedPatterns: [
      '@supabase/supabase-js',
      '@supabase/ssr',
      '../**/database.types',
      '../**/database.types.ts',
      '@/infrastructure/supabase/database.types',
      '@/infrastructure/supabase/database.types.ts',
    ],
    message:
      'App code must not import the Supabase SDK or generated Database types directly; call a typed feature-level module in src/infrastructure/supabase/ instead.',
  }),
  {
    files: ['src/app/**/*.{ts,tsx}'],
    plugins: { app: { rules: { 'no-supabase-access': noAppSupabaseAccess } } },
    rules: {
      'app/no-supabase-access': 'error',
    },
  },
  ...storybook.configs['flat/recommended'],
];
