-- v2 M4 (Issue #375, In Scope #1 / decisions.md "PO 判断: v2 の DB 方針" P5).
--
-- Every FK from a product table to auth.users(id) was declared without an
-- explicit ON DELETE clause (Postgres default: NO ACTION), except
-- catalog_creators.user_id (ON DELETE CASCADE, 20260822000200). oracle-
-- database.md §7 point 2 records this as an unintentional inconsistency,
-- not a decided policy - there is no account-deletion feature yet, so
-- nothing has ever exercised it.
--
-- decisions.md's P5 PO decision fixes the policy now, independent of when
-- an actual account-deletion feature ships (deleting a Supabase Auth user
-- directly, e.g. via the Admin API, already exercises these FKs today even
-- without a product-level "delete my account" UI):
--
--   shared catalog data (Event / Occurrence)      -> kept
--   personal data (participation / invitation /
--     personal schedule / ticket opportunity state) -> deleted
--
-- How each side is expressed as ON DELETE, and why:
--
-- - Personal data: ON DELETE CASCADE. These rows have no meaning once their
--   owning user is gone (a participation, a pending invitation, a personal
--   schedule entry, a ticket-planning state all *are* that user's data), so
--   removing them alongside the user is exactly "消す". This mirrors the
--   existing catalog_creators.user_id precedent, which already deletes a
--   permission row this same way.
--
-- - Shared catalog data (events.owner_id): ON DELETE NO ACTION, made
--   explicit rather than changed. "残す" (kept) means the Event row must
--   never be silently destroyed or silently orphaned as a side effect of
--   deleting a user - and owner_id is NOT NULL with no product-approved
--   "ownerless event" state (product-rules.md "Ownership": every Event has
--   an owner; owner transfer is not a supported operation; there is no
--   nullable-owner or ownerless-Event concept anywhere in product-rules.md
--   or oracle-database.md). Two mechanisms both technically "keep" the row:
--     (a) ON DELETE SET NULL - requires making owner_id nullable, which
--         invents a new "ownerless Event" product state (who may update it?
--         how does the UI render it?) that no PO decision has approved.
--     (b) ON DELETE NO ACTION - the row is preserved unconditionally
--         because the auth.users delete itself is refused while it would
--         orphan an Event; nothing about the Event ever changes.
--   (b) is chosen because it needs no new product state: deleting a
--   catalog-creator's auth user while they still own Events simply fails
--   until those Events are handled first - and product-rules.md's
--   "Deletion" section already gives the owner (or an operator) a real path
--   to do that (owner-only hard delete of an Event, provided its
--   Occurrences meet the existing delete preconditions). A future
--   account-deletion feature can require "no owned Events remain" as a
--   precondition using that existing capability, rather than this schema
--   inventing ownerless-Event semantics no product rule has approved.
--   event_occurrences has no direct auth.users FK (occurrence ownership is
--   derived from its parent Event, not stored on the row), so it needs no
--   change here.
--
-- Every FK below was declared inline (`references auth.users (id)`
-- with no explicit constraint name), so each one carries Postgres's default
-- autogenerated name (`<table>_<column>_fkey`) - confirmed against the
-- local Supabase instance (pg_constraint) rather than assumed. Postgres has
-- no `ALTER ... ALTER CONSTRAINT` for changing a FK's ON DELETE action in
-- place, so each is dropped and recreated with the same name and target,
-- adding only the ON DELETE clause. This changes no other property of the
-- constraint (same columns, same referenced table/column, NOT VALID is not
-- used - the existing data already satisfies plain FK validity, ON DELETE
-- has no bearing on validating existing rows).
--
-- Legacy safety: this only changes what happens when a referenced
-- auth.users row is deleted. Legacy has no account-deletion path today (no
-- code deletes auth.users rows), so no existing legacy behavior observes
-- this change; it only takes effect once something starts deleting
-- auth.users rows (the future account-deletion feature, or direct
-- Admin-API/service_role use).
alter table public.events
  drop constraint events_owner_id_fkey,
  add constraint events_owner_id_fkey
    foreign key (owner_id) references auth.users (id) on delete no action;

alter table public.personal_schedule_entries
  drop constraint personal_schedule_entries_owner_id_fkey,
  add constraint personal_schedule_entries_owner_id_fkey
    foreign key (owner_id) references auth.users (id) on delete cascade;

alter table public.personal_schedule_shares
  drop constraint personal_schedule_shares_shared_with_user_id_fkey,
  add constraint personal_schedule_shares_shared_with_user_id_fkey
    foreign key (shared_with_user_id) references auth.users (id) on delete cascade;

alter table public.occurrence_participations
  drop constraint occurrence_participations_user_id_fkey,
  add constraint occurrence_participations_user_id_fkey
    foreign key (user_id) references auth.users (id) on delete cascade;

alter table public.occurrence_invitations
  drop constraint occurrence_invitations_inviter_id_fkey,
  add constraint occurrence_invitations_inviter_id_fkey
    foreign key (inviter_id) references auth.users (id) on delete cascade;

alter table public.occurrence_invitations
  drop constraint occurrence_invitations_invitee_id_fkey,
  add constraint occurrence_invitations_invitee_id_fkey
    foreign key (invitee_id) references auth.users (id) on delete cascade;

alter table public.user_ticket_opportunity_states
  drop constraint user_ticket_opportunity_states_user_id_fkey,
  add constraint user_ticket_opportunity_states_user_id_fkey
    foreign key (user_id) references auth.users (id) on delete cascade;

-- catalog_creators.user_id already carries ON DELETE CASCADE
-- (20260822000200_create_catalog_creators.sql) and needs no change; it is
-- unchanged here only because it was already explicit and already correct
-- under this same policy (a creator-permission row is personal, not shared
-- catalog, data).
