-- v2 M4 (Issue #375, In Scope #1 / decisions.md "PO 判断: v2 の DB 方針" P5).
--
-- Every FK from a product table to auth.users(id) was declared without an
-- explicit ON DELETE clause (Postgres default: NO ACTION), except
-- catalog_creators.user_id (ON DELETE CASCADE, 20260822000200). oracle-
-- database.md §7 point 2 records this as an unintentional inconsistency,
-- not a decided policy - there is no account-deletion feature yet, so
-- nothing has ever exercised it.
--
-- decisions.md's P5 PO decision fixes the policy now, independent of when
-- an actual account-deletion feature ships (deleting a Supabase Auth user
-- directly, e.g. via the Admin API, already exercises these FKs today even
-- without a product-level "delete my account" UI):
--
--   shared catalog data (Event / Occurrence)      -> kept
--   personal data (participation / invitation /
--     personal schedule / ticket opportunity state) -> deleted
--
-- How each side is expressed as ON DELETE, and why:
--
-- - Personal data: ON DELETE CASCADE. These rows have no meaning once their
--   owning user is gone (a participation, a pending invitation, a personal
--   schedule entry, a ticket-planning state all *are* that user's data), so
--   removing them alongside the user is exactly "消す". This mirrors the
--   existing catalog_creators.user_id precedent, which already deletes a
--   permission row this same way.
--
-- - Shared catalog data (events.owner_id): ON DELETE NO ACTION, made
--   explicit rather than changed. "残す" (kept) means the Event row must
--   never be silently destroyed or silently orphaned as a side effect of
--   deleting a user - and owner_id is NOT NULL with no product-approved
--   "ownerless event" state (product-rules.md "Ownership": every Event has
--   an owner; owner transfer is not a supported operation; there is no
--   nullable-owner or ownerless-Event concept anywhere in product-rules.md
--   or oracle-database.md). Two mechanisms both technically "keep" the row:
--     (a) ON DELETE SET NULL - requires making owner_id nullable, which
--         invents a new "ownerless Event" product state (who may update it?
--         how does the UI render it?) that no PO decision has approved.
--     (b) ON DELETE NO ACTION - the row is preserved unconditionally
--         because the auth.users delete itself is refused while it would
--         orphan an Event; nothing about the Event ever changes.
--   (b) is chosen because it needs no new product state: deleting a
--   catalog-creator's auth user while they still own Events simply fails
--   until those Events are handled first - and product-rules.md's
--   "Deletion" section already gives the owner (or an operator) a real path
--   to do that (owner-only hard delete of an Event, provided its
--   Occurrences meet the existing delete preconditions). A future
--   account-deletion feature can require "no owned Events remain" as a
--   precondition using that existing capability, rather than this schema
--   inventing ownerless-Event semantics no product rule has approved.
--   event_occurrences has no direct auth.users FK (occurrence ownership is
--   derived from its parent Event, not stored on the row), so it needs no
--   change here.
--
-- Every FK below was declared inline (`references auth.users (id)`
-- with no explicit constraint name), so each one carries Postgres's default
-- autogenerated name (`<table>_<column>_fkey`) - confirmed against the
-- local Supabase instance (pg_constraint) rather than assumed. Postgres has
-- no `ALTER ... ALTER CONSTRAINT` for changing a FK's ON DELETE action in
-- place, so each must be dropped and recreated with the same name and
-- target, adding only the ON DELETE clause.
--
-- Legacy safety: this only changes what happens when a referenced
-- auth.users row is deleted. Legacy has no account-deletion path today (no
-- code deletes auth.users rows), so no existing legacy behavior observes
-- this change; it only takes effect once something starts deleting
-- auth.users rows (the future account-deletion feature, or direct
-- Admin-API/service_role use).
--
-- === PRODUCTION LOCK SAFETY (review finding on PR #378) ===
--
-- legacy shares this schema with a live production database, and tables
-- such as personal_schedule_entries / occurrence_participations already
-- hold real, growing row counts there - unlike the near-empty local dev
-- database this migration is developed against.
--
-- A plain `alter table t drop constraint old, add constraint old foreign
-- key (...) references auth.users (id) on delete cascade` recreates the FK
-- in one ALTER TABLE. Postgres validates every existing row against the
-- new constraint before that statement returns, and it does so while
-- holding ACCESS EXCLUSIVE on the table for the statement's *full*
-- duration (confirmed locally: a concurrent `select count(*)` against a
-- 200k-row table was blocked for the entire validation when reproduced
-- this way). ACCESS EXCLUSIVE blocks every other session's reads and
-- writes against the table, so on a production-sized table this migration
-- would stall legacy for as long as the FK validation scan takes.
--
-- This migration therefore only performs step 1 of the standard Postgres
-- "expand/validate" pattern for changing a FK's ON DELETE action without a
-- long-held ACCESS EXCLUSIVE lock, split across three separate migration
-- files (three separate transactions - see below for why that split is
-- necessary):
--
--   1. (this file, 20260908000000)  add each new FK as NOT VALID, under a
--                                    temporary `<name>_pending` constraint
--                                    name, leaving the existing (already
--                                    validated) constraint in place and
--                                    fully enforced throughout.
--   2. (20260908000010, next file)  VALIDATE CONSTRAINT the pending FKs.
--   3. (20260908000020, next file)  drop the old constraint and rename the
--                                    pending one to the final name.
--
-- Each step is its own migration file - and therefore its own transaction
-- - because Postgres locks are held until the end of the *transaction*,
-- not the end of the statement: doing ADD CONSTRAINT ... NOT VALID and
-- VALIDATE CONSTRAINT in the same transaction would still hold the ACCESS
-- EXCLUSIVE briefly taken by ADD CONSTRAINT for the entire VALIDATE
-- CONSTRAINT scan that follows it in that same transaction (reproduced
-- locally: a concurrent SELECT against the table blocked for the full
-- statement_timeout while VALIDATE ran inside the same open transaction as
-- the preceding ADD CONSTRAINT, but returned in ~15ms once ADD CONSTRAINT
-- and VALIDATE were split into separate, sequentially-committed
-- transactions instead).
--
-- Confirmed against the local Supabase CLI (v2.116.0, `supabase migration
-- up` / `supabase db reset`) that each migration file is applied as its
-- own transaction: a later file's failure does not roll back an earlier,
-- already-applied file's changes. Splitting this change across three
-- files is therefore sufficient on its own to get three separate
-- transactions when applied via `supabase db push` - no extra tooling or
-- manual `psql` step is required.
--
-- ADD CONSTRAINT ... NOT VALID (this file) still takes ACCESS EXCLUSIVE on
-- the target table, but only for the instant needed to add the catalog
-- entry - NOT VALID means Postgres skips scanning existing rows at ADD
-- time, so the lock here is held for a moment, not for a table-scan's
-- duration. No legacy stall is expected from this file. New writes are
-- still fully checked against the pending FK from the moment this file
-- commits (NOT VALID only means "not yet checked against pre-existing
-- rows"; it does not weaken enforcement for anything written afterward).
--
-- No cross-file ordering dependency on any other migration in this
-- repository, and no Vercel deploy depends on this migration (application
-- code never reads pg_constraint), so this is `post-deploy-safe` per
-- docs/architecture/runtime-stack.md's ordering fence. This file and the
-- next two should be applied together in one maintenance pass, but the
-- intermediate states between them are all valid and safe to leave
-- applied for a while if needed (two FKs enforcing the same reference is
-- redundant but harmless).
alter table public.events
  add constraint events_owner_id_fkey_pending
    foreign key (owner_id) references auth.users (id) on delete no action
    not valid;

alter table public.personal_schedule_entries
  add constraint personal_schedule_entries_owner_id_fkey_pending
    foreign key (owner_id) references auth.users (id) on delete cascade
    not valid;

alter table public.personal_schedule_shares
  add constraint personal_schedule_shares_shared_with_user_id_fkey_pending
    foreign key (shared_with_user_id) references auth.users (id) on delete cascade
    not valid;

alter table public.occurrence_participations
  add constraint occurrence_participations_user_id_fkey_pending
    foreign key (user_id) references auth.users (id) on delete cascade
    not valid;

alter table public.occurrence_invitations
  add constraint occurrence_invitations_inviter_id_fkey_pending
    foreign key (inviter_id) references auth.users (id) on delete cascade
    not valid;

alter table public.occurrence_invitations
  add constraint occurrence_invitations_invitee_id_fkey_pending
    foreign key (invitee_id) references auth.users (id) on delete cascade
    not valid;

alter table public.user_ticket_opportunity_states
  add constraint user_ticket_opportunity_states_user_id_fkey_pending
    foreign key (user_id) references auth.users (id) on delete cascade
    not valid;

-- catalog_creators.user_id already carries ON DELETE CASCADE
-- (20260822000200_create_catalog_creators.sql) and needs no change; it is
-- unchanged here only because it was already explicit and already correct
-- under this same policy (a creator-permission row is personal, not shared
-- catalog, data).
